### ISSUE TITLE
Bad nesting of container, row and col-**-** structure

### ISSUE THREAD

**Issue by tammoterhark** [Shnoulle/LimeSurvey-Shnoulle#11] opened 2016-08-25 09:59 UTC
TODO
======
- [x]  5 point default choice : move to form-input
- [x] radio list : 
- [x] checkbox list
- [x] date input
- [x] date dropdown
- [x] Yes no button : see 5 point
- [x] Gender button : see 5 point
- [x] Yes no radio
- [x] Gender radio
In the views in the default theme there is bad nesting. 

From getbootstrap.com:
==========================
Introduction

Grid systems are used for creating page layouts through a series of rows and columns that house your content. Here's how the Bootstrap grid system works:

- Rows must be placed within a .container (fixed-width) or .container-fluid (full-width) for proper alignment and padding.
- Use rows to create horizontal groups of columns.
- Content should be placed within columns, and only columns may be immediate children of rows.
- Predefined grid classes like .row and .col-xs-4 are available for quickly making grid layouts. Less mixins can also be used for more semantic layouts.
- Columns create gutters (gaps between column content) via padding. That padding is offset in rows for the first and last column via negative margin on .rows.
- The negative margin is why the examples below are outdented. It's so that content within grid columns is lined up with non-grid content.
- Grid columns are created by specifying the number of twelve available columns you wish to span. For example, three equal columns would use three .col-xs-4.
- If more than 12 columns are placed within a single row, each group of extra columns will, as one unit, wrap onto a new line.
- Grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes, and override grid classes targeted at smaller devices. Therefore, e.g. applying any .col-md-* class to an element will not only affect its styling on medium devices but also on large devices if a .col-lg-* class is not present.

Look to the examples for applying these principles to your code.
===============================

So: each group of cols should be in a .row and not nested.

I can make changes for that and send as a pull request.

**Comment by Shnoulle** [comment] 2016-08-25 15:29
Looking at patch : it seems an issue in default template only ? 

I think this patch is separated from {ANSWERS} html, no ?

Then i think we can separate this and make a pull request on official directly. O don't want to patch default template a lot in THIS fork.

PS : col-sm-12 + col-sm-6 : please remove one :)

**Comment by tammoterhark** [comment] 2016-08-25 15:34
Can you please make a pull request on the official LS repo? I am already struggling very much to learn Git. This was my first pull request and I have no idea how to connect my repo to the official LS repo. I am connected to your repo now.

And yes, for now this is on the default template only. I think that should be enough for now...

**Comment by tammoterhark** [comment] 2016-08-25 15:34
And where did you see that col-sm-12 and col-sm-6?

**Comment by Shnoulle** [comment] 2016-09-02 13:35
Here : https://github.com/toolsforresearch/LimeSurvey-Shnoulle/commit/06e17e90535151842f29164849d6046d7432bd5c#diff-3c8cbe50572c509e0257b889dc9e35e8R20

Finally it's col-sm-6 (the last won)

**Comment by tammoterhark** [comment] 2016-09-02 14:07
OK, whatever you need. Will this be in your fork and will this make it into core?

**Comment by Shnoulle** [comment] 2016-09-02 15:30
The issue is in template, i don't really want to fix template : only fix core HTML and do our own better template ;) than default.

. But i see some bad usage of col-sm etc ....

ANd : i'm unsure we need to fix it everywhere. For example : actually the home page add a col-sm-6 on each survey title. Maybe it's cool when you have a lot of surveys, but with only one is ... bad. I don't think we need a col-sm-X here : just leave the template to do what he want.

Denis
PS: maybe not merged actually for the surveys listing

**Comment by tammoterhark** [comment] 2016-09-08 14:28
Shall I close this one?

**Comment by tammoterhark** [comment] 2016-09-08 14:28
Just ignore the pull request.

**Comment by Shnoulle** [comment] 2016-09-08 16:38
Maybe you can fix the default template. Testing seems difficult actually

**Comment by tammoterhark** [comment] 2016-09-08 17:00
I guess I will have to test this against the current version of LimeSurvey, so on a limesurvey clone, not on your clone...

**Comment by Shnoulle** [comment] 2016-09-09 06:01
Looking at actual default template a lot of div ....

**Comment by tammoterhark** [comment] 2016-09-09 06:45
I will look at it. And see what I can do with my limited powers.

**Comment by LouisGac** [comment] 2016-09-09 08:22
Well Bootstrap logic implies a lot of div. 
If there is unnecessary ones, good to remove them. But, IMHO, it would be useless to try to reduce the number of div just by principle.

**Comment by tammoterhark** [comment] 2016-09-09 08:28
Agreed, let's not be fundamentalistic about it. Louis, shall I "repair" the default template on Shnoulle's clone? If that works, we can do the other two afterwards.

**Comment by tammoterhark** [comment] 2016-09-09 08:33
When I do it om Denis' clone, it is automatically in sync with the edited views.

**Comment by LouisGac** [comment] 2016-09-09 08:34
Well, if the default template works as before, you can be 100% we'll do the merge quickly.

**Comment by Shnoulle** [comment] 2016-10-05 16:54
@tammoterhark : can you have a look at {ANSWERS} part if we have a row each time we have a col-sm-x please ?

And put the list of "question to be fixed here"

**Comment by tammoterhark** [comment] 2016-10-06 08:15
Denis, shall I make new issues with what I find? I assume you want me to test the **default** template on row and col-xx-xx issues?

**Comment by tammoterhark** [comment] 2016-10-06 08:15
Other comments (apart form row/col issues) not here?

**Comment by tammoterhark** [comment] 2016-10-06 08:20
In yes/no question there is nested col- statement. Shall I make a commit, or do you prefer to do this yourself, so there will be cionsistency. I might do it in another way than you...

**Comment by tammoterhark** [comment] 2016-10-06 08:20
Same for gender (like in yes/no)

**Comment by tammoterhark** [comment] 2016-10-06 08:23
![5point](https://cloud.githubusercontent.com/assets/6483317/19145340/cee35300-8bae-11e6-9894-a282105da339.png)

Incorrect alignment of radio buttons in 5 point choice

**Comment by tammoterhark** [comment] 2016-10-06 08:47
![mc](https://cloud.githubusercontent.com/assets/6483317/19146055/127952d8-8bb2-11e6-90d4-788c2253bcce.png)

Difference between 2 question types. I cannot find where ul class="list-unstyled checkbox-list answers-list col-sm-12 col-xs-12" is generated. It should be preceded by <div class="row">

**Comment by tammoterhark** [comment] 2016-10-06 08:58
![radio](https://cloud.githubusercontent.com/assets/6483317/19146412/b4042320-8bb3-11e6-805b-92491db6e160.png)

Radio also. But again I cannot find the ul declaration. Where is that?

**Comment by Shnoulle** [comment] 2016-10-06 09:16
Already fixed single and radio 5 (but not pushed)

singe and multiple : it's due to usage of "multiple column"

multiple comment don't have "col-sm-X" ? If not needed : we don't add it ? Right ?

**Comment by tammoterhark** [comment] 2016-10-06 09:18
Just curious: where is that ul declaration? I could not find it in views...

**Comment by tammoterhark** [comment] 2016-10-06 09:19
I would only add it if it is necessary. Bootstrap is a tool, not a religion..

**Comment by Shnoulle** [comment] 2016-10-06 09:21
For the ul : inside "column-start.php"

OK : then no need for radio-5 and multiple with comment

**Comment by tammoterhark** [comment] 2016-10-06 09:28
Where is column-start.php?

**Comment by tammoterhark** [comment] 2016-10-06 09:34
This looks like progress! ;-)

**Comment by tammoterhark** [comment] 2016-10-06 09:41
Nested cols in date question

![date](https://cloud.githubusercontent.com/assets/6483317/19147715/be9c0acc-8bb9-11e6-95e5-64104fa46d73.png)

**Comment by tammoterhark** [comment] 2016-10-06 09:44
I have commit ready for first date question, not for second one. Cannot find where to put .row....

**Comment by tammoterhark** [comment] 2016-10-06 09:59
Also found the second one

**Comment by tammoterhark** [comment] 2016-10-06 10:02
Have to go now. Back this afternoon.

**Comment by Shnoulle** [comment] 2016-10-06 10:06
@tammoterhark : sorry , for pull request : can you do it in https://github.com/LimeSurvey/LimeSurvey/tree/answers_html ?

This is now the origin/official version

**Comment by Shnoulle** [comment] 2016-10-07 16:36
Seems done , if another : reopen here and here : https://bugs.limesurvey.org/view.php?id=11735

**Closed by Shnoulle** 2016-10-07 16:36 UTC
